# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s.split()


['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
print('The diameter of {} is {} kilometers.' .format(planet,diameter));


The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
print(d['k1'][3]["tricky"][3]['target'][3])


hello


# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
import numpy as np 
array=np.zeros(10) 
print("An array of 10 zeros:") 
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
import numpy as np 
array=np.ones(10)*5 
print("An array of 10 fives:") 
print(array)


An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [10]:
import numpy as np 
array=np.arange(20,36,2) 
print("Array of all the even integers from 20 to 35") 
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
import numpy as np 
x=np.arange(0,9).reshape(3,3) 
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
a=np.array([1,2,3]) 
print(a) 
b=np.array([4,5,6]) 
print(b) 
print('\n----Result of a and b----') 
print(np.concatenate((a,b)))


[1 2 3]
[4 5 6]

----Result of a and b----
[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [13]:
import pandas as pd


In [14]:
data=[10,20,30] 
d=pd.DataFrame(data, columns=['Numbers']) 
print(d)

   Numbers
0       10
1       20
2       30


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [15]:
import pandas as pd 
from dateutil.parser import parse 
date_series=pd.Series(['Jan 2023' , 'Feb 2023']) 
print("Original Series:") 
print(date_series)

Original Series:
0    Jan 2023
1    Feb 2023
dtype: object


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [16]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [17]:
import pandas as pd 
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]] 
df = pd.DataFrame(lists, columns =['Fnumber', 'name','Lnumber']) 
print(df )

   Fnumber name  Lnumber
0        1  aaa       22
1        2  bbb       25
2        3  ccc       24
