# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
x=s.split(",")

In [ ]:
print(x)

['Hi there Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print("The diameter of {} is{} kilometer.".format(planet,diameter))

The diameter of Earth is12742 kilometer.


In [ ]:
print(f"The diameter of{planet} is {diameter} kilometer.")

The diameter ofEarth is 12742 kilometer.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
array=np.zeros(10)

In [ ]:
print("An array of 10 zeros:")

An array of 10 zeros:


In [ ]:
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array=np.ones(10)*5

In [ ]:
print("An array of 10 fives:")

An array of 10 fives:


In [ ]:
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np

In [ ]:
array=np.arange(20,35,2)

In [ ]:
print("Array of all the even integers from 20 to 35")

Array of all the even integers from 20 to 35


In [ ]:
print(array)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np

In [ ]:
x=np.arange(2,11).reshape(3,3)

In [ ]:
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a=np.array([1,2,3])

In [ ]:
b=np.array([4,5,6])

In [ ]:
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
data=[10,20,30]

In [ ]:
d=pd.DataFrame(data,columns=['Numbers'])

In [ ]:
print(d)

   Numbers
0       10
1       20
2       30


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
from dateutil.parser import parse

In [ ]:
date_series=pd.Series(['Jan 2023','Feb 2023'])

In [ ]:
print("oringinal Series:")

oringinal Series:


In [ ]:
print(date_series)

0    Jan 2023
1    Feb 2023
dtype: object


In [ ]:
print("\nNew dates:")


New dates:


In [ ]:
result=date_series.map(lambda d: parse('11'+d))

In [ ]:
print(result)

0   2023-01-11
1   2023-02-11
dtype: datetime64[ns]


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
d=pd.DataFrame(lists,columns=['numbers','Tag','numbers'])

In [ ]:
print(d)

   numbers  Tag  numbers
0        1  aaa       22
1        2  bbb       25
2        3  ccc       24
